version: '3.8'

networks:
  my-network:
    external: true

services:
  nginx:
    hostname: project1-nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ./
    image: my-nginx
#    ports:
#      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - my-data_project1:/var/www
    networks:
      - my-network
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project1.rule=Host(`project1.laravel.test`)"
  php-fpm:
    hostname: project1-php
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    image: my-php-fpm
    ports:
      - "5173:5173"
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - my-data_project1:/var/www
    networks:
      - my-network
  project1:
    build:
      dockerfile: docker/project1/Dockerfile
      context: ./
    image: project1:1.0
    volumes:
      - my-data_project1:/var/www
    networks:
      - my-network
  #      - ./:/var/www
volumes:
  my-data_project1:
